# CircleCI 2.0 configuration file

version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: echo $CIRCLE_TAG > version.txt
      - run: docker build -t anthoitaker/randall:$CIRCLE_TAG .
      - run: docker build -t anthoitaker/randall .
      - run: docker push anthoitaker/randall:$CIRCLE_TAG
      - run: docker push anthoitaker/randall
  deploy:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: printenv > .env
      - run: make fab-update
      - run: make fab-deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
