# CircleCI 2.0 configuration file

version: 2

jobs:

  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: echo $CIRCLE_TAG > version.txt
      - run: docker build -t anthoitaker/randall:$CIRCLE_TAG .
      - run: docker build -t anthoitaker/randall .

  lint:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: bash utils/envvars/export.sh
      - run: make lint

  test:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: bash utils/envvars/export.sh
      - run: make test

  push:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker push anthoitaker/randall:$CIRCLE_TAG
      - run: docker push anthoitaker/randall

  deploy:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "50:0a:21:c1:3a:1e:7a:c2:f7:48:5d:0e:94:5c:2f:d8"
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: bash utils/envvars/export.sh
      - run: make fab-update
      - run: make fab-deploy

workflows:
  version: 2
  integration:
    jobs:

      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

      - lint:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

      - test:
          requires:
            - lint
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

      - push:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/

      - deploy:
          requires:
            - push
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
