# CircleCI 2.0 configuration file

version: 2

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t anthoitaker/randall .
      - run: docker push anthoitaker/randall

workflows:
  version: 2
  CI:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
